version: '3'

services:
  react:
        container_name: react-app
        stdin_open: true
        build: ../podkins/.
        ports:
          - "3000:3000"
  node:
      container_name: podkins
      restart: always
      build: .
      ports:
        - "8080:8080"
      links:
        - mongo
  mongo:
      container_name: mongodb
      image: mongo
      ports:
        - "27017:27017"

